package com.todoreminder.data.local

import androidx.room.Entity
import androidx.room.PrimaryKey


/**
 * Represents a reminder item stored in the local Room database.
 *
 * Each reminder has a title, description, scheduled time, and optional recurrence configuration.
 *
 * @property id The unique ID of the reminder. Auto-generated by Room.
 * @property title The title of the reminder.
 * @property description A more detailed description of the reminder.
 * @property dateTime The scheduled time of the reminder in milliseconds since epoch.
 * @property isRecurring Indicates whether the reminder should repeat at regular intervals.
 * @property recurrenceInterval The interval (in minutes) at which the reminder recurs.
 */
@Entity(tableName = "reminders")
data class ReminderEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val title: String,
    val description: String,
    val dateTime: Long,
    val isRecurring: Boolean,
    val recurrenceInterval: Long
)
